#!/usr/bin/env python3
# -*- coding: utf-8 -*-

subset = [
    "ground truth",
    "muss-mined",
    "muss-wiki-mined",
    "openai-text-ada-001",
    "openai-text-babbage-001",
    "openai-text-curie-001",
    "openai-text-davinci-002",
    "openai-text-davinci-003",
    "openai-gpt-3.5-turbo",
    "bloom",
    "bloomz",
    "opt-1.3b",
    "opt-30b",
    "opt-iml-max-1.3b",
    "opt-iml-max-30b",
    "flan-t5-small",
    "flan-t5-base",
    "flan-t5-large",
    "flan-t5-xl",
    "flan-t5-xxl",
    "flan-ul2",
]

model_name_map = {
    "ground truth": "Gold References",
    "muss-mined": "MUSS-mined",
    "muss-wiki-mined": "MUSS-wiki-mined",
    "openai-text-ada-001": "OpenAI Ada-001",
    "openai-text-babbage-001": "OpenAI Babbage-001",
    "openai-text-curie-001": "OpenAI Curie-001",
    "openai-text-davinci-002": "OpenAI Davinci-002",
    "openai-text-davinci-003": "OpenAI Davinci-003",
    "openai-gpt-3.5-turbo": "OpenAI GPT-3.5-Turbo",
    "bloom-560m": "BLOOM-560m",
    "bloom-1b1": "BLOOM-1b1",
    "bloom-3b": "BLOOM-3b",
    "bloom-7b1": "BLOOM-7b1",
    "bloom": "BLOOM",
    "bloomz-560m": "BLOOMZ-560m",
    "bloomz-1b1": "BLOOMZ-1b1",
    "bloomz-3b": "BLOOMZ-3b",
    "bloomz-7b1": "BLOOMZ-7b1",
    "bloomz": "BLOOMZ",
    "gpt-j-6b": "GPT-J-6b",
    "gpt-neox-20b": "GPT-NeoX-20b",
    "llama-7b": "LLaMA-7b",
    "llama-13b": "LLaMA-13b",
    "llama-30b": "LLaMA-30b",
    "llama-65b": "LLaMA-65b",
    "opt-1.3b": "OPT-1.3b",
    "opt-6.7b": "OPT-6.7b",
    "opt-13b": "OPT-13b",
    "opt-30b": "OPT-30b",
    "opt-66b": "OPT-66b",
    "opt-iml-max-1.3b": "OPT-IML-MAX-1.3b",
    "opt-iml-max-30b": "OPT-IML-MAX-30b",
    "t0-3b": "T0-3b",
    "t0": "T0",
    "t0pp": "T0pp",
    "t5-small-lm-adapt": "T5-small",
    "t5-base-lm-adapt": "T5-base",
    "t5-large-lm-adapt": "T5-large",
    "t5-xl-lm-adapt": "T5-xl",
    "t5-xxl-lm-adapt": "T5-xxl",
    "flan-t5-small": "Flan-T5-small",
    "flan-t5-base": "Flan-T5-base",
    "flan-t5-large": "Flan-T5-large",
    "flan-t5-xl": "Flan-T5-xl",
    "flan-t5-xxl": "Flan-T5-xxl",
    "ul2": "UL2",
    "flan-ul2": "Flan-UL2",
}

test_name_map = {
    'asset-test': 'ASSET',
    'news-manual-all-test': 'Newsela',
    'med-easi-test': 'Med-EASI',
}

if __name__ == '__main__':
    pass